[package]
name = "hwatch-diffmode"
version = "0.3.19"
edition = "2021"

[dependencies]
ratatui = { version = "0.28.0", default-features = false, features = [
    'crossterm',
    'unstable-rendered-line-info',
] }
ansi_term = "0.12.1"
